// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.roo.test.domain;

import com.roo.test.domain.Product;

privileged aspect Product_Roo_JavaBean {
    
    public String Product.getName() {
        return this.Name;
    }
    
    public void Product.setName(String Name) {
        this.Name = Name;
    }
    
}
